In [1]:
import numpy as np
import analysis
s = np.array([0, 0, 1, 0, 2, 2, 2])
n = 3
m = 4
seq= np.array([[0, 1, 1, 1],
               [0, 0, 1, 0],
               [0, 0, 1, 0],
               [0, 1, 0, 0],
               [1, 0, 0, 1],
               [1, 1, 0, 0],
               [0, 1, 0, 1]])

hmm = analysis.HMM4binary_sensors()
hmm.fit_with_true_hidden_states(seq, s)
print(hmm.predict_states(seq))
print(hmm.A)
print(hmm.P)

(array([0, 1, 0, 2, 2, 2, 2]), 5.873606637142921e-07)
[[0.33333333 0.33333333 0.33333333]
 [1.         0.         0.        ]
 [0.         0.         1.        ]]
[[0.         0.66666667 0.66666667 0.33333333]
 [0.         0.         1.         0.        ]
 [0.66666667 0.66666667 0.         0.66666667]]


In [3]:
import numpy as np
import analysis
C = np.array([1/2, 1/2])
A = np.array([[1/4, 3/4],
              [1/4, 3/4]])
P = np.array([[4/5, 1/5],
              [1/5, 2/3]])
s = np.random.randint(0, 2)
states = [s]
data = [[np.random.binomial(1, P[s][0]), np.random.binomial(1, P[s][1])]]
for i in range(10000):
    flag = np.random.binomial(1, A[s][0])
    if s == 0:        
        if not(flag):
            s = 1
    else:
        if flag:
            s = 0
    states.append(s)
    data.append([np.random.binomial(1, P[s][0]), np.random.binomial(1, P[s][1])])
states = np.array(states)
data = np.array(data)

hmm = analysis.HMM4binary_sensors()
hmm.fit_with_true_hidden_states(data, states)
print(hmm.C)
print(hmm.A)
print(hmm.P)

[0. 1.]
[[0.25408204 0.74591796]
 [0.25023368 0.74976632]]
[[0.79299363 0.21218153]
 [0.20269729 0.67071705]]


In [8]:
import numpy as np

C = np.array([0.9, 0.1])
P = np.array([[0.5, 0.5, 0.5, 0.5],
              [0.1, 0.1, 0.9, 0.9]])
o_t = np.array([0, 0, 1, 1])
ones_vec = np.ones(o_t.shape[0])
L = [C[i] * np.prod(P[i]*o_t + (ones_vec - P[i])*np.abs((ones_vec - o_t))) for i in range(P.shape[0])]
print(L)

[0.05625, 0.06561000000000002]


In [17]:
def logsub(logX, logY):
        """
        This calculates log(X - Y) from log(X) and log(Y).
        
        Parameters
        ----------
        logX : float
        logY : float
        
        Returns
        -------
        ret : float
        """
        if logX < logY:
            raise ValueError('logX must be larger than logY')
        if logX == float('inf'):
            return logX
        diff = logY - logX
        if diff < -20:
            return logX
        return logX + np.log(1 - np.exp(diff))

n = 3
m = 2
logC = np.array([-1, -2, -3])
P = np.array([[0.5, 0.5],
              [0.3, 0.7],
              [0.1, 0.9]])
logP = np.log(P)
log1P = np.array([[logsub(0, logP[i][j]) for j in range(m)] for i in range(n)])
o_t = np.array([1, 0])
ones_vec = np.array([1, 1])

logp = [logC[i] + np.sum(logP[i]*o_t + log1P[i]*(ones_vec - o_t)) for i in range(n)]
ret = np.argmax(logp)
prob = np.max(logp)

print(ret)
print(prob)

0
-2.386294361119891


In [18]:
logp = [logC[i] + np.sum(logP[i]*o_t + log1P[i]*(ones_vec - o_t)) for i in range(n)]
logp = logC + 
ret = np.argmax(logp)
prob = np.max(logp)

print(ret)
print(prob)

SyntaxError: invalid syntax (Temp/ipykernel_4796/2185474609.py, line 2)